# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yi Liu
#description: >- # this means to ignore newlines until "baseurl:"
  #Bay is a minimal Jekyll Theme.
#baseurl: "/bay" # the subpath of the site
#url: "https://www.eliottvincent.com/" # the base hostname & protocol for the site
#og_image: /assets/img/profile-pic.jpg
#google_analytics: "UA-121636368-3"

header:
  pages:
    - name: About
      slug: /
    - name: Publications
    - name: CV

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: yliu297@ncsu.edu
      link: mailto:yliu297@ncsu.edu
  follow:
    - name: Twitter
      link: https://twitter.com/YiLiu1998
      username: "@YiLiu1998"
    - name: LinkedIn
      link: https://www.linkedin.com/in/yiliu98

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
